# workflow that deploys code added to master branch
name: continuous deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v2

    # pull the latest commit from the repo to production directory
    - name: Get the latest commit and deploy it
      run: |
        chmod +x continuous.sh
        ./continuous.sh

# discord notification
    
    # if job succeds
    - name: Discord notification - success
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: "Inter-Net: lates commit to master branch has been integrated into production! No let's celebrate!"
    # if job fails
    - name: Discord notification - success
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Inter-Net: failed to get the latest commit into production. Someone fucked something up!'
