# workflow that deploys code added to master branch
name: continuous deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v2

    # pull the latest commit from the repo to production directory
    - name: Get the latest commit and deploy it
      run: |
        chmod +x continuous.sh
        ./continuous.sh
