# test workflow on every pull request
name: testing suite

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

# specify Node.js version
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # checkout to current branch
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    # install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
    
    # discord notification
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Discord Notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '${{ steps.extract_branch.outputs.branch }}: {{ GITHUB_ACTOR }} new pull request passed all tests! Ready to merge!'
