# test workflow on every pull request
name: testing suite

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

# specify Node.js version
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    # checkout to current branch
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    # install node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true
    
    # discord notification
    
    # if job succeds
    - name: Discord notification - success
      if: success()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Inter-Net: {{ GITHUB_ACTOR }} - your new pull request passed all tests! Ready to merge!'
    # if job fails
    - name: Discord notification - success
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Inter-Net: {{ GITHUB_ACTOR }} - your new pull request did not pass shit. Go back to work!'
